Added slurm integration
1. Generalized scheduler implementation to be updated by any user.
2. Specialized implementation for prolog and epilog script for slurm and flux and general.

diff --git a/scripts/datacrumbs/datacrumbs_server_run.sh.in b/scripts/datacrumbs/datacrumbs_server_run.sh.in
--- a/scripts/datacrumbs/datacrumbs_server_run.sh.in
+++ b/scripts/datacrumbs/datacrumbs_server_run.sh.in
@@ -14,7 +14,7 @@ fi
 source "$SCRIPT_DIR/datacrumbs_args"
 
 dc_args_init "DATACRUMBS"
-dc_args_add_option "DATACRUMBS" "composite-name" "OPTIONAL" "Composable name" "string"
+dc_args_add_option "DATACRUMBS" "composite-name" "OPTIONAL" "Composable name" "string" "$DATACRUMBS_COMPOSABLE_NAME"
 dc_args_add_option "DATACRUMBS" "enable-mpi" "OPTIONAL" "switch to enable MPI" "bool" "0"
 dc_args_add_option "DATACRUMBS" "nodes" "OPTIONAL" "Set number of nodes" "int" "1"
 dc_args_add_option "DATACRUMBS" "ppn" "OPTIONAL" "Set processes per node" "int" "1"
@@ -37,24 +37,20 @@ PROG_NAME=$(basename "$0")
 source $SCRIPT_DIR/datacrumbs_setup
 
 if [[ "$DATACRUMBS_COMPOSITE_NAME" != "" ]] && [[ "$DATACRUMBS_COMPOSITE_NAME" != "NONE" ]]; then
-    if [[ ! -f "${DATACRUMBS_CLIENT_BIN}/datacrumbs_${DATACRUMBS_COMPOSITE_NAME}" ]]; then
-        error "Composite ${DATACRUMBS_COMPOSITE_NAME} not found for ${DATACRUMBS_USER}"
+    if ! validate_datacrumbs_composite_name "${DATACRUMBS_COMPOSITE_NAME}"; then
+        error "Invalid composable name: ${DATACRUMBS_COMPOSITE_NAME}"
         exit 1
     fi
 fi
 
 
 check_sudo_user
-
-RUNID=${!DATACRUMBS_JOB_ID_VAR}
-RUNID=${RUNID:-1000}
-DATACRUMBS_LOG_FILE=${DATACRUMBS_LOG_DIR}/datacrumbs_${DATACRUMBS_USER}_${RUNID}.log
-READY_FILE="@DATACRUMBS_INSTALL_RUNSTATEDIR@/datacrumbs_${DATACRUMBS_USER}_${RUNID}.ready"
-debug "RUNID: $RUNID"
+    
+debug "DATACRUMBS_SERVER_RUN_ID: $DATACRUMBS_SERVER_RUN_ID"
 debug "DATACRUMBS_JOB_ID_VAR: $DATACRUMBS_JOB_ID_VAR"
 debug "value DATACRUMBS_JOB_ID_VAR: ${!DATACRUMBS_JOB_ID_VAR}"
 debug "DATACRUMBS_LOG_FILE: $DATACRUMBS_LOG_FILE"
-debug "READY_FILE: $READY_FILE"
+debug "DATACRUMBS_SERVER_READY_FILE: $DATACRUMBS_SERVER_READY_FILE"
 log "Running as USER = $DATACRUMBS_USER and storing traces in $DATACRUMBS_TRACE_DIR and log file $DATACRUMBS_LOG_FILE"
 datacrumbs_init $DATACRUMBS_USER $DATACRUMBS_TRACE_DIR
 exec=()
diff --git a/scripts/datacrumbs/datacrumbs_service_common.sh.in b/scripts/datacrumbs/datacrumbs_service_common.sh.in
--- a/scripts/datacrumbs/datacrumbs_service_common.sh.in
+++ b/scripts/datacrumbs/datacrumbs_service_common.sh.in
@@ -2,42 +2,141 @@
 
 set -e pipefail
 
-FLUX_DATACRUMBS=$(flux job info $FLUX_JOB_ID jobspec | jq -r .attributes.system.datacrumbs)
+source @DATACRUMBS_INSTALL_BINARYDIR@/datacrumbs_setup
 
-warn_user() {
-    ## post exception to flux log, cancel job
-    flux job raise --severity=1 ${FLUX_JOB_ID}  "datacrumbs-prolog: $@"
+function get_general_datacrumbs_enabled() {
+    local enabled=${DATACRUMBS_ENABLED:-0}
+    enabled_value="no"
+    if [[ "${enabled}" -eq "1" ]]; then
+        enabled_value="yes"
+    fi
+    log_system "get_general_datacrumbs_enabled returned enabled:${enabled_value}"
+    echo "${enabled_value}"
 }
 
-if [[ ${FLUX_DATACRUMBS} == "null" ]]; then
-    logger "User hasn't requested datacrumbs feature, exiting."
-    return 1
-fi
-FLUX_DATACRUMBS=$(flux job info $FLUX_JOB_ID jobspec | jq -r .attributes.system.datacrumbs.enable)
-if [[ ${FLUX_DATACRUMBS} == "null" || "${FLUX_DATACRUMBS}" != "yes" ]]; then
-    logger "User hasn't requested datacrumbs feature, exiting."
-    return 1
-fi
+function get_flux_datacrumbs_enabled() {
+    local enabled=$(flux job info $FLUX_JOB_ID jobspec 2>/dev/null | jq -r .attributes.system.datacrumbs 2>/dev/null)
+    enabled_value="no"
+    if [[ ${enabled} == "null" ]]; then
+        log_system "User hasn't requested datacrumbs feature  enabled:${enabled}, exiting."
+    else
+        FLUX_DATACRUMBS=$(flux job info $FLUX_JOB_ID jobspec 2>/dev/null | jq -r .attributes.system.datacrumbs.enable 2>/dev/null)
+        if [[ ${FLUX_DATACRUMBS} == "null" || "${FLUX_DATACRUMBS}" != "yes" ]]; then
+            log_system "User hasn't requested datacrumbs feature  FLUX_DATACRUMBS:${FLUX_DATACRUMBS}, exiting."
+        else 
+            enabled_value="yes"
+        fi
+    fi
+    log_system "get_flux_datacrumbs_enabled returned enabled:${enabled_value}"
+    echo "${enabled_value}"
+}
 
-FLUX_DATACRUMBS_COMPOSE=$(flux job info $FLUX_JOB_ID jobspec | jq -r .attributes.system.datacrumbs.composite)
-if [[ ${FLUX_DATACRUMBS_COMPOSE} == "null"  || ${FLUX_DATACRUMBS_COMPOSE} == "" ]]; then
-    DATACRUMBS_COMPOSABLE_NAME="NONE"
-    logger "User hasn't requested datacrumbs' composite feature using ${DATACRUMBS_COMPOSABLE_NAME}."
+function get_slurm_comment() {
+  local slurm_job_comment=$(scontrol show job $SLURM_JOB_ID | grep -i comment | awk -F'=' '{print $2}')
+  echo $slurm_job_comment
+}
+
+function get_slurm_datacrumbs_enabled() {
+  enabled_value="no"
+  local slurm_job_comment=$(get_slurm_comment)
+  # NOTE: If SLURM_JOB_COMMENT which is a JSON
+  # of format {datacrumbs: {enable: "yes|no", composite: name}}.
+  # says datacrumbs enable is yes, else remains the same.
+  if [[ $(echo ${slurm_job_comment} | jq -r .datacrumbs.enable 2>/dev/null) == "yes" ]]; then
+    enabled_value="yes"
+  fi
+  log_system "get_slurm_datacrumbs_enabled returned enabled:${enabled_value}"
+  echo "${enabled_value}"
+}
+
+function get_datacrumbs_enabled() {
+    local enabled="no"
+    if [[ "FLUX" == "@DATACRUMBS_SCHEDULER_TYPE@" ]]; then
+        enabled=$(get_flux_datacrumbs_enabled)
+    elif [[ "@DATACRUMBS_SCHEDULER_TYPE@" == "SLURM" ]]; then
+        local slurm_job_comment=$(get_slurm_comment)
+        log_system "Slurm comment: $slurm_job_comment"
+        enabled=$(get_slurm_datacrumbs_enabled)
+    else
+        enabled=$(get_general_datacrumbs_enabled)
+    fi
+    log_system "get_datacrumbs_enabled returned enabled:${enabled}"
+    echo "${enabled}"
+}
+
+function get_flux_datacrumbs_composite_name() {
+    local composite_name=$(flux job info $FLUX_JOB_ID jobspec | jq -r .attributes.system.datacrumbs.composite 2>/dev/null)
+    if [[ ${composite_name} == "null"  || ${composite_name} == "" ]]; then
+        log_system "User hasn't requested datacrumbs' composite feature using ${composite_name}.""ERROR"
+    else
+        log_system "User has requested datacrumbs' composite feature using ${composite_name}."
+    fi
+    log_system "get_flux_datacrumbs_composite_name returned composite_name:${composite_name}"
+    echo "${composite_name}"
+}
+
+function get_slurm_datacrumbs_composite_name() {
+  local composite_name=$(get_default_datacrumbs_composite_name)
+  local slurm_job_comment=$(get_slurm_comment)
+  local slurm_composite="$(echo ${slurm_job_comment} | jq -r .datacrumbs.composite 2>/dev/null)"
+  if [[
+    ${slurm_composite} == "" ||
+    ${slurm_composite} == "NONE" ||
+    ${slurm_composite} == "null" ||
+    ${slurm_composite} == $(get_default_datacrumbs_composite_name) ]] \
+    ; then
+    log_system "User hasn't requested datacrumbs' composite feature using ${composite_name}"
+  else
+    log_system "User has requested datacrumbs' composite feature using ${composite_name}."
+  fi
+  log_system "get_slurm_datacrumbs_composite_name returned composite_name:${composite_name}"
+  echo "${composite_name}"
+}
+
+function get_general_datacrumbs_composite_name() {
+  local composite_name=$(get_default_datacrumbs_composite_name)
+  if [[ ${DATACRUMBS_COMPOSITE_NAME} == "null" || ${composite_name} == "" ]]; then
+    log_system "User hasn't requested datacrumbs' composite feature using ${composite_name}."
+  else
+    log_system "User has requested datacrumbs' composite feature using ${composite_name}."
+  fi
+  log_system "get_general_datacrumbs_composite_name returned composite_name:${composite_name}"
+  echo "${composite_name}"
+}
+
+function get_datacrumbs_composite_name() {
+    local name=$(get_default_datacrumbs_composite_name)
+    if [[ "FLUX" == "@DATACRUMBS_SCHEDULER_TYPE@" ]]; then
+        name=$(get_flux_datacrumbs_composite_name)
+    elif [[ "@DATACRUMBS_SCHEDULER_TYPE@" == "SLURM" ]]; then
+        name=$(get_slurm_datacrumbs_composite_name)
+    else
+        name=$(get_general_datacrumbs_composite_name)
+    fi
+    if [[ "${name}" != "$(get_default_datacrumbs_composite_name)" && "${name}" != "ERROR" ]]; then  
+        if ! validate_datacrumbs_composite_name "${name}"; then
+            name="ERROR"
+        fi
+    fi
+    log_system "get_datacrumbs_composite_name returned name:${name}"
+    echo "${name}"
+}
+
+DATACRUMBS_ENABLED=$(get_datacrumbs_enabled)
+if [[ "${DATACRUMBS_ENABLED}" != "yes" ]]; then
+    log_system "User hasn't requested datacrumbs feature, exiting."
+    return 1
+fi
+DATACRUMBS_COMPOSABLE_NAME=$(get_datacrumbs_composite_name)
+if [[ "${DATACRUMBS_COMPOSABLE_NAME}" == "ERROR" ]]; then
+    return 1
+fi
+if [[ "${DATACRUMBS_COMPOSABLE_NAME}" == "$(get_default_datacrumbs_composite_name)" ]]; then
+    log_user "Running system datacrumbs"
 else
-    DATACRUMBS_COMPOSABLE_NAME=${FLUX_DATACRUMBS_COMPOSE}
-    if [[ -n "$FLUX_JOB_USERID" ]]; then
-        DATACRUMBS_USER=$(id -nu $FLUX_JOB_USERID)
-    fi
-    if [[ ! -f "@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_LIBEXECDIR@/@PROJECT_NAME@/@CMAKE_INSTALL_SBINDIR@/${DATACRUMBS_USER}/datacrumbs_${DATACRUMBS_COMPOSABLE_NAME}" ]]; then
-        warn_user "Error: Composable name ${DATACRUMBS_COMPOSABLE_NAME} does not exist."
-        return 1
-    fi
-    logger "User has requested datacrumbs' composite feature using ${DATACRUMBS_COMPOSABLE_NAME}."
+    log_user "Running a composite datacrumbs with name: ${DATACRUMBS_COMPOSABLE_NAME}"
 fi
 
-if [[ ! ${DATACRUMBS_COMPOSABLE_NAME} =~ ^[a-zA-Z_]+$ ]]; then
-    warn_user "Error: DATACRUMBS_COMPOSABLE_NAME: ${DATACRUMBS_COMPOSABLE_NAME} contains invalid characters. Only alphabets and underscores are allowed."
-    return 1
-fi
-
+readonly DATACRUMBS_COMPOSABLE_NAME
 export DATACRUMBS_COMPOSABLE_NAME
+export DATACRUMBS_USER
