The composable names are checked in user's and install user's directory.
1. Allows us to precompose some probes for users.
2. fixed logging to system vs user.

diff --git a/scripts/datacrumbs/datacrumbs_compose_wrapper.in b/scripts/datacrumbs/datacrumbs_compose_wrapper.in
--- a/scripts/datacrumbs/datacrumbs_compose_wrapper.in
+++ b/scripts/datacrumbs/datacrumbs_compose_wrapper.in
@@ -12,4 +12,9 @@ check_sudo_user
 DATACRUMBS_COMPOSABLE_NAME=$1
 shift
 
+if ! validate_datacrumbs_composite_name "${DATACRUMBS_COMPOSABLE_NAME}"; then
+    error "Invalid composable name: ${DATACRUMBS_COMPOSABLE_NAME}"
+    exit 1
+fi
+
 ${DATACRUMBS_CLIENT_BIN}/datacrumbs_${DATACRUMBS_COMPOSABLE_NAME} $@
diff --git a/scripts/datacrumbs/datacrumbs_server_run.sh.in b/scripts/datacrumbs/datacrumbs_server_run.sh.in
--- a/scripts/datacrumbs/datacrumbs_server_run.sh.in
+++ b/scripts/datacrumbs/datacrumbs_server_run.sh.in
@@ -37,8 +37,8 @@ PROG_NAME=$(basename "$0")
 source $SCRIPT_DIR/datacrumbs_setup
 
 if [[ "$DATACRUMBS_COMPOSITE_NAME" != "" ]] && [[ "$DATACRUMBS_COMPOSITE_NAME" != "NONE" ]]; then
-    if [[ ! -f "${DATACRUMBS_CLIENT_BIN}/datacrumbs_${DATACRUMBS_COMPOSITE_NAME}" ]]; then
-        error "Composite ${DATACRUMBS_COMPOSITE_NAME} not found for ${DATACRUMBS_USER}"
+    if ! validate_datacrumbs_composite_name "${DATACRUMBS_COMPOSITE_NAME}"; then
+        error "Invalid composable name: ${DATACRUMBS_COMPOSITE_NAME}"
         exit 1
     fi
 fi
