add linting for sh and cmake files.

diff --git a/scripts/datacrumbs/datacrumbs_create_log_dir.in b/scripts/datacrumbs/datacrumbs_create_log_dir.in
--- a/scripts/datacrumbs/datacrumbs_create_log_dir.in
+++ b/scripts/datacrumbs/datacrumbs_create_log_dir.in
@@ -6,8 +6,8 @@ SCRIPT_DIR=@DATACRUMBS_INSTALL_BINARYDIR@
 
 # Check if datacrumbs_args exists in scripts directory
 if [[ ! -f "$SCRIPT_DIR/datacrumbs_args" ]]; then
-    echo "Error: datacrumbs_args not found in $SCRIPT_DIR"
-    exit 1
+	echo "Error: datacrumbs_args not found in $SCRIPT_DIR"
+	exit 1
 fi
 
 # Source argument parser
@@ -27,9 +27,9 @@ done
 
 dc_args_parse "$APP" "datacrumbs_create_log_dir" "$@"
 if [[ $? -ne 0 ]]; then
-    echo "Error: Argument parsing failed."
-    show_help
-    exit 1
+	echo "Error: Argument parsing failed."
+	show_help
+	exit 1
 fi
 
 PROG_NAME=$(basename "$0")
diff --git a/scripts/datacrumbs/datacrumbs_server_stop.sh.in b/scripts/datacrumbs/datacrumbs_server_stop.sh.in
--- a/scripts/datacrumbs/datacrumbs_server_stop.sh.in
+++ b/scripts/datacrumbs/datacrumbs_server_stop.sh.in
@@ -6,8 +6,8 @@ SCRIPT_DIR=@DATACRUMBS_INSTALL_BINARYDIR@
 
 # Check if datacrumbs_args exists in scripts directory
 if [[ ! -f "$SCRIPT_DIR/datacrumbs_args" ]]; then
-    echo "Error: datacrumbs_args not found in $SCRIPT_DIR"
-    exit 1
+  echo "Error: datacrumbs_args not found in $SCRIPT_DIR"
+  exit 1
 fi
 
 # Source argument parser
@@ -23,33 +23,30 @@ dc_args_add_subcommand "DATACRUMBS" "enable-mpi" "1" "nodes" "ppn"
 dc_args_parse "DATACRUMBS" "datacrumbs_run" "$@"
 
 if [[ $? -ne 0 ]]; then
-    echo "Error: Argument parsing failed."
-    show_help
-    exit 1
+  echo "Error: Argument parsing failed."
+  show_help
+  exit 1
 fi
 
 export DATACRUMBS_JOB_ENABLE_MPI=${DATACRUMBS_ENABLE_MPI:-0}
 export DATACRUMBS_JOB_NODES=${DATACRUMBS_NODES:-1}
 export DATACRUMBS_JOB_PPN=${DATACRUMBS_PPN:-1}
 
-
 PROG_NAME=$(basename "$0")
 
 source $SCRIPT_DIR/datacrumbs_setup
 
 if [[ "$DATACRUMBS_COMPOSITE_NAME" != "" ]] && [[ "$DATACRUMBS_COMPOSITE_NAME" != "NONE" ]]; then
-    if [[ ! -f "${DATACRUMBS_CLIENT_BIN}/datacrumbs_${DATACRUMBS_COMPOSITE_NAME}" ]]; then
-        error "Composite ${DATACRUMBS_COMPOSITE_NAME} not found for ${DATACRUMBS_USER}"
-        exit 1
-    fi
+  if [[ ! -f "${DATACRUMBS_CLIENT_BIN}/datacrumbs_${DATACRUMBS_COMPOSITE_NAME}" ]]; then
+    error "Composite ${DATACRUMBS_COMPOSITE_NAME} not found for ${DATACRUMBS_USER}"
+    exit 1
+  fi
 fi
 
 # Convert APP_CMD string into array, splitting on spaces
-read -ra APP_CMD <<< "${DATACRUMBS_APP}"
-
+read -ra APP_CMD <<<"${DATACRUMBS_APP}"
 
 check_sudo_user
-
 
 debug "DATACRUMBS_SERVER_RUN_ID: $DATACRUMBS_SERVER_RUN_ID"
 debug "DATACRUMBS_JOB_ID_VAR: $DATACRUMBS_JOB_ID_VAR"
@@ -60,9 +57,9 @@ echo "Running cmd: ${APP_CMD[*]} as USER = $DATACRUMBS_USER and storing traces i
 
 exec=()
 if [[ "$DATACRUMBS_COMPOSITE_NAME" != "" ]] && [[ "$DATACRUMBS_COMPOSITE_NAME" != "NONE" ]]; then
-    exec=("${DATACRUMBS_INSTALL_SBIN_DIR}/datacrumbs_compose_wrapper" "${DATACRUMBS_COMPOSITE_NAME}")
+  exec=("${DATACRUMBS_INSTALL_SBIN_DIR}/datacrumbs_compose_wrapper" "${DATACRUMBS_COMPOSITE_NAME}")
 else
-    exec=(@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_SBINDIR@/datacrumbs)
+  exec=(@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_SBINDIR@/datacrumbs)
 fi
 
 datacrumbs_stop_server "${exec[*]}" $PROG_NAME
