The composable names are checked in user's and install user's directory.
1. Allows us to precompose some probes for users.
2. fixed logging to system vs user.

diff --git a/scripts/datacrumbs/datacrumbs_compose_run.in b/scripts/datacrumbs/datacrumbs_compose_run.in
--- a/scripts/datacrumbs/datacrumbs_compose_run.in
+++ b/scripts/datacrumbs/datacrumbs_compose_run.in
@@ -13,7 +13,7 @@ source "$SCRIPT_DIR/datacrumbs_args"
 
 # Initialize argument parser for this script
 dc_args_init "DATACRUMBS_COMPOSE_RUN"
-dc_args_add_option "DATACRUMBS_COMPOSE_RUN" "composite_name" "MANDATORY" "Composable name" "string"
+dc_args_add_option "DATACRUMBS_COMPOSE_RUN" "composite_name" "MANDATORY" "Composable name" "string" "${DATACRUMBS_COMPOSABLE_NAME}"
 dc_args_add_option "DATACRUMBS_COMPOSE_RUN" "app" "MANDATORY" "App command" "string"
 dc_args_add_option "DATACRUMBS_COMPOSE_RUN" "enable_mpi" "OPTIONAL" "switch to enable MPI" "bool" "0"
 dc_args_add_option "DATACRUMBS_COMPOSE_RUN" "nodes" "OPTIONAL" "Set number of nodes" "int" "1"
@@ -38,7 +38,7 @@ export DATACRUMBS_JOB_ENABLE_MPI=${DATACRUMBS_COMPOSE_RUN_ENABLE_MPI:-0}
 export DATACRUMBS_JOB_NODES=${DATACRUMBS_COMPOSE_RUN_NODES:-1}
 export DATACRUMBS_JOB_PPN=${DATACRUMBS_COMPOSE_RUN_PPN:-1}
 
-if [[ -z "$DATACRUMBS_COMPOSABLE_NAME" ]]; then
+if [[ -z "$DATACRUMBS_COMPOSABLE_NAME" || "$DATACRUMBS_COMPOSABLE_NAME" == "NONE" ]]; then
     echo "Error: COMPOSITE_NAME argument is required."
     show_help
     exit 1
@@ -47,6 +47,11 @@ fi
 if [[ -z "${DATACRUMBS_COMPOSE_RUN_APP}" ]]; then
     echo "Error: APP command is required."
     show_help
+    exit 1
+fi
+
+if ! validate_datacrumbs_composite_name "${DATACRUMBS_COMPOSABLE_NAME}"; then
+    error "Invalid composable name: ${DATACRUMBS_COMPOSABLE_NAME}"
     exit 1
 fi
 
@@ -69,6 +74,10 @@ debug "DATACRUMBS_JOB_ID_VAR: $DATACRUMBS_JOB_ID_VAR"
 debug "value DATACRUMBS_JOB_ID_VAR: ${!DATACRUMBS_JOB_ID_VAR}"
 debug "DATACRUMBS_LOG_FILE: $DATACRUMBS_LOG_FILE"
 debug "DATACRUMBS_SERVER_READY_FILE: $DATACRUMBS_SERVER_READY_FILE"
+
+
+
+
 exec=("${DATACRUMBS_INSTALL_SBIN_DIR}/datacrumbs_compose_wrapper" "${DATACRUMBS_COMPOSABLE_NAME}")
 debug "Starting datacrumbs server with exec: ${exec[*]}"
 datacrumbs_start_server "${exec[*]}"
